backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
locale: 'ru'

collections:
  - name: "config"
    label: "Настройки"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Настройки сайта"
        file: "config.json"
        description: "Основные настройки сайта: ключевые слова, заголовки, аккаунты в соц. сетях"
        fields:
          - label: "Адрес сайта"
            name: "base_url"
            widget: "string"
            hint: "Не вводите / в конце адреса"
          - label: "Заголовок сайта"
            name: "site_title"
            widget: "string"
          - label: "Описание сайта"
            name: "site_description"
            widget: "string"
          - label: "Ключевые слова"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Твиттер аккаунт"
            name: "twitter_account"
            widget: "string"
          - label: "Гитхаб аккаунт"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Константы"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Авторы"
        file: "meta/authors.yml"
        description: "Авторы и их описание"
        fields:
          - name: authors
            label: Авторы
            label_singular: "Автор"
            widget: list
            fields:
              - label: "Никнейм для URL-адреса"
                name: "slug"
                widget: "string"
                hint: "Только латиница. Будет отображаться в URL-адресе автора его личной страницы"
              - label: "Имя автора"
                name: "name"
                widget: "string"
                hint: "Имя и фамилия"
              - label: "Описание, добавьте пару строк, о том чем он занимается"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Теги"
        file: "meta/tags.yml"
        description: "Список тегов"
        fields:
          - name: tags
            label: Теги
            label_singular: "Тег"
            widget: list
            fields:
              - label: "URL-адрес тега"
                name: "slug"
                widget: "string"
                hint: "Только латиница. Будет частью URL-адреса страницы тега"
              - label: "Имя для отображения"
                name: "name"
                widget: "string"
                hint: "Тут уже как-угодно. Будет отображаться в статьях или других материалах"

  - name: "posts"
    label: "Записи в блоге"
    folder: "content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "URL-адрес записи"
        name: "slug"
        widget: "string"
      - label: "Заголовок"
        name: "title"
        widget: "string"
      - label: "Дата публикации"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "Автор"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Теги
        label_singular: "Тег"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Тег
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Текст"
        name: "body"
        widget: "markdown"
